package cool.android.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cool.food.android.bean.RestaurantBean;
import cool.food.android.bean.FoodBean;

import cool.android.greendao.RestaurantBeanDao;
import cool.android.greendao.FoodBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig restaurantBeanDaoConfig;
    private final DaoConfig foodBeanDaoConfig;

    private final RestaurantBeanDao restaurantBeanDao;
    private final FoodBeanDao foodBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        restaurantBeanDaoConfig = daoConfigMap.get(RestaurantBeanDao.class).clone();
        restaurantBeanDaoConfig.initIdentityScope(type);

        foodBeanDaoConfig = daoConfigMap.get(FoodBeanDao.class).clone();
        foodBeanDaoConfig.initIdentityScope(type);

        restaurantBeanDao = new RestaurantBeanDao(restaurantBeanDaoConfig, this);
        foodBeanDao = new FoodBeanDao(foodBeanDaoConfig, this);

        registerDao(RestaurantBean.class, restaurantBeanDao);
        registerDao(FoodBean.class, foodBeanDao);
    }
    
    public void clear() {
        restaurantBeanDaoConfig.clearIdentityScope();
        foodBeanDaoConfig.clearIdentityScope();
    }

    public RestaurantBeanDao getRestaurantBeanDao() {
        return restaurantBeanDao;
    }

    public FoodBeanDao getFoodBeanDao() {
        return foodBeanDao;
    }

}
