package cool.android.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cool.food.android.bean.FoodBean;
import cool.food.android.bean.RestaurantBean;

import cool.android.greendao.FoodBeanDao;
import cool.android.greendao.RestaurantBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodBeanDaoConfig;
    private final DaoConfig restaurantBeanDaoConfig;

    private final FoodBeanDao foodBeanDao;
    private final RestaurantBeanDao restaurantBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodBeanDaoConfig = daoConfigMap.get(FoodBeanDao.class).clone();
        foodBeanDaoConfig.initIdentityScope(type);

        restaurantBeanDaoConfig = daoConfigMap.get(RestaurantBeanDao.class).clone();
        restaurantBeanDaoConfig.initIdentityScope(type);

        foodBeanDao = new FoodBeanDao(foodBeanDaoConfig, this);
        restaurantBeanDao = new RestaurantBeanDao(restaurantBeanDaoConfig, this);

        registerDao(FoodBean.class, foodBeanDao);
        registerDao(RestaurantBean.class, restaurantBeanDao);
    }
    
    public void clear() {
        foodBeanDaoConfig.clearIdentityScope();
        restaurantBeanDaoConfig.clearIdentityScope();
    }

    public FoodBeanDao getFoodBeanDao() {
        return foodBeanDao;
    }

    public RestaurantBeanDao getRestaurantBeanDao() {
        return restaurantBeanDao;
    }

}
